version: 0.2
phases:
  install:
    commands:
      - echo "test"
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) | sed 's,https://,,g'
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - export docker_registry_host=$(echo $REPOSITORY_URI | sed 's=/.*==g')
  build:
    commands:
      - echo Build started on `date`
      - docker build --rm=false --build-arg="build=$CODEBUILD_BUILD_ID" -t $REPOSITORY_URI:$TAG .
      - export docker_build_container_id=$(docker ps -a --filter "label=image=build" --filter "label=build=$CODEBUILD_BUILD_ID" --filter "status=exited" --format "{{.ID}}")
      - docker push $REPOSITORY_URI:$TAG
    finally:
      - docker cp $docker_build_container_id:/project/build/test-results test-results
  post_build:
    commands:
      - printenv
      - echo Build completed on `date`
      - printf '[{"name":"simple-project","imageUri":"%s"}]' "$REPOSITORY_URI:$TAG" > imagedefinitions.json
reports: #New
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'test-results' # Location of the reports
artifacts:
  files: imagedefinitions.json