version: '3'

services:
  simplebackend:
    container_name: simplebackend
    build: .
    environment:
      - "SPRING_PROFILES_ACTIVE=postgres"
    ports:
      - 8080:8080

  postgres:
    container_name: postgres
    image: postgres:12.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=hello

